name: Compile

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  THEOS: ""
  VERSION: "0.0.0-0"

jobs:
  fetch-and-release:
    runs-on: macos-14
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Install Dependencies
        run: |
          echo /usr/local/opt/make/libexec/gnubin >> $GITHUB_PATH
          echo /opt/homebrew/opt/make/libexec/gnubin >> $GITHUB_PATH
          HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install dpkg ldid-procursus make xcbeautify openssl@3
          VERSION_FILE="TrollFools/Version.xcconfig"
          VERSION_MAIN=$(grep "VERSION" $VERSION_FILE | cut -d'=' -f2 | tr -d '[:space:]')
          VERSION_BUILD=$(grep "BUILD_NUMBER" $VERSION_FILE | cut -d'=' -f2 | tr -d '[:space:]')
          VERSION=$VERSION_MAIN-$VERSION_BUILD
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"

      - name: Checkout THEOS
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          ref: 942cd0c015f93d8c2d714ba0c69e7f420157c382
          path: theos
          submodules: recursive

      - name: Add THEOS environment variables
        run: |
          rm -rf $GITHUB_WORKSPACE/theos/sdks
          echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
          echo "THEOS_PACKAGE_SCHEME=rootless" >> $GITHUB_ENV
          echo "FINALPACKAGE=1" >> $GITHUB_ENV

      - name: Checkout SDKs
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/sdks
          ref: master
          path: ${{ env.THEOS }}/sdks

      - name: Checkout ChOma
        uses: actions/checkout@v4.1.1
        with:
          repository: opa334/ChOma
          ref: e270219e20214cc9b654ac2d48b96540be5bc0fd
          path: choma

      - name: Build Current ChOma Helper
        run: |
          sed -i '' 's/csd_code_directory_update(realCodeDirBlob, macho);/csd_code_directory_update_code_slots(realCodeDirBlob, macho);/' choma/tests/ct_bypass/main.c
          make -C choma TARGET=ios DISABLE_TESTS=1
          make -C choma TARGET=ios output/ios/tests/ct_bypass
          cp choma/output/ios/tests/ct_bypass TrollFools/ct_bypass
          ldid -S TrollFools/ct_bypass

      - name: Build Packages
        run: |
          make package
          cp packages/*.tipa packages/*.deb .
          find .theos/obj -name "*.dSYM" -exec cp -r {} . \;

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: TrollFools-iOS18-${{ env.VERSION }}
          if-no-files-found: error
          path: |
            *.tipa
            *.deb
            *.dSYM
